apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-dev
  namespace: dev
  labels:
    app: mlflow-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model
  template:
    metadata:
      labels:
        app: mlflow-model
    spec:
      containers:
      - name: mlflow-model
        # Use the locally built Docker image for the MLflow model
        image: mlflow-model:latest
        ports:
        - containerPort: 8000
        env:
        # MLflow Tracking URI pointing to the local MLflow server
        - name: MLFLOW_TRACKING_URI
          value: "http://localhost:5000"
        # Name of the registered model in the MLflow Model Registry
        - name: MODEL_NAME
          value: "adult-classifier"
        # Path to the model artifact (if required)
        - name: MODEL_ARTIFACT_PATH
          value: "/mlflow/artifacts"
        resources:
          # Resource limits and requests for local development
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        # Mount the external storage directory into the container
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlflow/artifacts
      volumes:
      # Volume for accessing MLflow artifacts stored on external storage
      - name: mlflow-artifacts
        hostPath:
          # Example: Path to the directory on the external storage device
          path: /D:/ci-cd-volumes/mlflow-artifacts/dev
          type: Directory