apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-secret-access
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["redis-secret"]
    verbs: ["get"]